Vagrant.configure("2")do|config|
  config.vm.box="centos/7"
  config.vm.network "private_network", ip: "192.168.2.11"
  config.vm.hostname = "node1.tp2.b2"
  config.vm.provision "shell", path: "script/script.sh"

  # Ajoutez cette ligne afin d'accélérer le démarrage de la VM (si une erreur 'vbguest' est levée, voir la note un peu plus bas)
  config.vbguest.auto_update = false

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false

  config.vm.define :node1 do |t|
  end

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true
  # config de la ram
config.vm.provider "virtualbox" do |v|
        v.memory = 1024
        v.name = "node1.tp2.b2"
    end

end
